### ISSUE TITLE
Missing LabID's in TDatesRadio

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/BugsCEP#1]
# Problem:
Numerous radiometric date records (290?) have LabNR but no LabID. Is results in a flag in SEAD import.
# Solution:
Phil needs to add the missing LabID's in bugsdata. Most are existing labs identifiable from the LabNr.
# Requires:
Pause in data entry from Paul.

**Comment by visead** [comment]
SEAD import handles import of null, " " and "Unknown" LabID's.

Bugsdata needs checking and null and " " replacing with "Unknown"

**Comment by visead** [comment]
Sorted out where possible. One unknown LabNr left to check up but might be a typo in the original publication (SSR) - have set this to Unknown.
NOTE: Only Radiocarbon labs have LabID's according to an international standard list. Other dates will often produce the no lab flag as they have no lab in the lookup TLabs list.
